<? $this->md5_compil='a4972d658a368bddebbe3a9528d4b30d'; ?>
<div class="mainContentBlockFullWidth">
  <div class="contentLeft">
    <div class="title">
      <?php echo $this->get("order.top.html"); ?>
    </div>
    <div class="body">
      
      <div class="borderedTwoCol">
        <div style="border:none;" class="register colLeft">
          <div class="blockContent">
            <h1>Оплата заказа прошла успешно!</h1>
    

            <div class="btnContainer">
              <a class="btnBlue" href="/ru/cabinet/#/history"> Посмотреть статус заказа <span class="arrowRight"></span></a>
            </div>
          </div>
        </div>
      </div>
          
      
    </div>
  </div>
  <div class="contentRight">
  	
    <div class="body">
    	<?php echo $this->get("order.sidebar.html"); ?>
    </div>
  </div>
</div>
