<? $this->md5_compil='59a37ba8a0e02844672cc80ee89e0a62'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/menu.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.core-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.excheck-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.exedit-3.5.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/css/zTreeStyle.css" rel="stylesheet">

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Меню <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
