<? $this->md5_compil='225fc20c722b7d303fad63ab9d3091fe'; ?>
<div class="control-group">
  <table class="table table-hover">
    <tr>
      <td><img src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>img/f.png"></td>
      <td><input type="text" name="social_fb" module-id="<?php if(isset($this->vars['moduleId'])) echo $this->vars['moduleId']; ?>" value="<?php if(isset($this->vars['moduleInfo']['social_fb'])) echo $this->vars['moduleInfo']['social_fb']; ?>"></td>
    </tr>
    <tr>
      <td><img src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>img/t.png"></td>
      <td><input type="text" name="social_tw" module-id="<?php if(isset($this->vars['moduleId'])) echo $this->vars['moduleId']; ?>" value="<?php if(isset($this->vars['moduleInfo']['social_tw'])) echo $this->vars['moduleInfo']['social_tw']; ?>"></td>
    </tr>
    <tr>
      <td><img src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>img/B.png"></td>
      <td><input type="text" name="social_vk" module-id="<?php if(isset($this->vars['moduleId'])) echo $this->vars['moduleId']; ?>" value="<?php if(isset($this->vars['moduleInfo']['social_vk'])) echo $this->vars['moduleInfo']['social_vk']; ?>"></td>
    </tr>
    <tr>
      <td><img src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>img/You.png"></td>
      <td><input type="text" name="social_yt" module-id="<?php if(isset($this->vars['moduleId'])) echo $this->vars['moduleId']; ?>" value="<?php if(isset($this->vars['moduleInfo']['social_yt'])) echo $this->vars['moduleInfo']['social_yt']; ?>"></td>
    </tr>
  </table>

</div>

