<? $this->md5_compil='4c51f3aabcb63565bcc7a57ebd1c71b7'; ?>

<div class="row-fluid">
	<div class="widget smallWidget">
		<div class="widget-title">
          <h4><i class="icon-reorder"></i>Структура сайта</h4>
      	</div>
      	<div class="widget-body">
          <a href="javascript:void(0)" onclick="site_control.createPage('html')" class="btn btn-success"><i class="icon-plus"></i> Создать страницу</a>
                    
          <a href="javascript:void(0)" action="editPage" class="btn btn-primary disabled"><i class="icon-edit"></i> Редактировать</a>
          <a href="javascript:void(0)" action="removePage" class="btn btn-danger disabled"><i class="icon-trash"></i> Удалить</a>

          
          <br>
          <br>
          <ul class="basic_tree ztree" id="pages-tree"></ul>
      	</div>
  	</div>
</div>

