<? $this->md5_compil='90f620e943a22dddfdaba917523e8398'; ?>
<div class="row-fluid">
  <div class="span12">
    <div class="widget smallWidget">
      <div class="widget-title">
        <h4><i class="icon-user"></i>Изменить пароль</h4>                
      </div>
      <div class="widget-body">
        <form class="form-horizontal">
          <div class="control-group">
            <label class="control-label">Новый пароль</label>
            <div class="controls">
              <input class="require" type="text" name="wordkey" value="">
              <span class="passMessage"></span>
            </div>
          </div>
          <div class="control-group">
          	<div class="controls passProgress" >
              <div>Стойкость пароля:</div>
              
            </div>
          </div>
          <button type="button" action="save" class="btn btn-success">Сохранить</button>
          <button type="button" action="back" class="btn">Назад</button>
        </form>
        
      </div>
    </div>
  </div>
</div>