<? $this->md5_compil='3c0a58a0cbd16a4c93f3431df1bc01d4'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.order.js?v0.0.6" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.core-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.excheck-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.exedit-3.5.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/css/zTreeStyle.css" rel="stylesheet">

<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Заказы <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
