<? $this->md5_compil='6cf932a1477f1ed84eadda26ef63202c'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.shop.js?v3.1" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/shop.js?v0.1" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/cropper-master/dist/cropper.min.js"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/cropper.js" type="text/javascript"></script>

<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/cropper-master/dist/cropper.min.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/container.padding.fix.css" rel="stylesheet">

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Каталог товаров <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
