<? $this->md5_compil='4d2dd463384224a71a07ca237874b480'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.vendors.js" type="text/javascript"></script>
<script type="text/javascript" src="/plugins/ckeditor/ckeditor.js"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">



<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Производители <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
