<? $this->md5_compil='b9a0d03a79896559e011a0dc9e152a7e'; ?>
<h1>Изменить пароль</h1>
<div class="small-form">
  <form class="form-horizontal">
    <div class="control-group">
      <label class="control-label">Текущий пароль <span>*</span></label>
      <div class="controls"><input type="password" name="oldpass" class="span8 require"></div>
    </div>
    <div class="control-group">
      <label class="control-label">Новый пароль <span>*</span></label>
      <div class="controls"><input type="password" name="newpass1" class="span8 require"></div>
    </div>
    <div class="control-group">
      <label class="control-label">Новый пароль еще раз <span>*</span></label>
      <div class="controls"><input type="password" name="newpass2" class="span8 require"></div>
    </div>

    <div class="control-group">
      <label class="control-label">
      	<a href="javascript:void(0)" action="back" class="btnGray" style="font-weight: normal;">Назад</a>
      </label>
      <div class="controls"> 
        <a href="javascript:void(0)" action="save" class="btnBlue">Сохранить</a>
      </div>
    </div>
  </form>
</div>