<? $this->md5_compil='882d1286d41bff86fa8575d666e26b9b'; ?>
<div class="space20"></div>
<div class="space20"></div>
<div class="widget-body">
  <div style="min-height: 800px" class="error-page">
    <img alt="maintenances" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>img/500.png">
    <h1>
      <strong style="font-size:38px">Сервис не доступен!</strong> <br>
      <p style="font-size:24px; line-height:27px;">В настоящий момент мы обновляем наше ПО. <br>
        Сервис будет не доступен некоторое время.</p>
    </h1>
  </div>
</div>