<? $this->md5_compil='bc6be164eb5a51bdb68ab234af7ecae7'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/theme_admin.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Управление темами <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
