<? $this->md5_compil='d69762e99ea68251f017f788cd9fd94d'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/cropper-master/dist/cropper.min.js"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.min.js"></script>
<script src="/plugins/ckeditor/ckeditor.js"></script>

<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.theme_setting.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/cropper.js" type="text/javascript"></script>

<link href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/cropper-master/dist/cropper.min.css" rel="stylesheet">
<link href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">
<link href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.css" rel="stylesheet"/>  

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Настройка дизайна <small>стили оформения, дополнительные модули и прочее</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>





