<? $this->md5_compil='bef38c24d80bb83c90c1ee1ffa58e409'; ?>

<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.clients.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/md5crypt.js" type="text/javascript"></script>


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Клиенты <small>Клиенты сервиса</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>

