<? $this->md5_compil='c9ab308ada4b549bd72ec42fe2e11eb1'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/uploader.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.core-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.excheck-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.exedit-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/pages.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/css/zTreeStyle.css" rel="stylesheet">


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Сайт <small>управление страницами сайта</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
