<? $this->md5_compil='485dff5d3db7402fc54820bf64ccad16'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/settings.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/bootstrap-wizard/jquery.bootstrap.wizard.min.js"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/elevatezoom-master/jquery.elevateZoom-3.0.8.min.js"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/multiselect/multiselect.js"></script>

<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/assets/multiselect/style.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Управление сайтами</h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
 