<? $this->md5_compil='9c2f41cbc332803d34847f4c19f1d02e'; ?>
<script type="text/javascript" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/plugins/ckeditor/ckeditor.js"></script>
<link rel="stylesheet" type="text/css" href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.css" />  
<?php if(isset($this->vars['controller_content'])) echo $this->vars['controller_content']; ?>
