<? $this->md5_compil='e8b98599d18718300aa799a3bf9ad19c'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.shop_clients.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">

<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Клиенты <small></small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
