<? $this->md5_compil='d4594de643666a5b8fba35438bea2658'; ?>
<div class="mainContentBlock mainInfo">

  <div class="left">
    <span>
      <div>Приветствуем вас в нашем интернет-магазине крепежных изделий.</div>
      Среди широкого ассортимента товаров вы сможете легко найти то, что нужно, узнать о наличии на складе, сделать заказ, оплатить покупку и <br>оформить доставку.  
    </span>
    <div class="actions">
      <a href="/about/" class="aboutLink">О магазине</a>
      <!-- <a href="/faq/" class="helpLink">Помощь</a> -->
    </div>
  </div>

  <div class="center">
    <div class="slider centerSlider">
      <div class="container jcarousel">
        <ul>
          <!-- Рекламный Баннер №1 
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b1.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3b>
                     Чистим снег<br />лопатами<br />Prosperplast
                   </h3b>
                </div>
                <a href="/lopati_skrebki_ledorubi/" class="link">перейти</a>
              </div>
            </div>            
          </li> -->
        <!-- Рекламный Баннер №2 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b2.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3>
                     <br /> <br />ДИСКИ ДЛЯ ОБРАБОТКИ<br />ДЕРЕВА БОЛГАРКОЙ
                   </h3>
                </div>
                <a href="/diski_dlya_obrabotki_dereva/" class="link">перейти</a>
              </div>
            </div>            
          </li>
  <!-- Рекламный Баннер №3 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b3.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3>
                     <br /> <br />ПЕРФОРИРОВАННЫЙ КРЕПЁЖ ИЗ РОССИИ
                   </h3>
                </div>
                <a href="/ru/shop/category/id/89/" class="link">перейти</a>
              </div>
            </div>            
          </li>
        <!-- Рекламный Баннер №4 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b4.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3>
                     Клейкие ленты KLL<br />в ассортименте
                   </h3>
                </div>
                <a href="/klejkie_lenty_kll/" class="link">перейти</a>
              </div>
            </div>            
          </li>
        <!-- Рекламный Баннер №5 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b5.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3g>
                     Самонарезающие<br />шурупы<br />для деревянных конструкций
                   </h3g>
                </div>
                <a href="/shurupi_samonarezayushtie_dlya_dereva/" class="link">перейти</a>
              </div>
            </div>            
          </li>
      <!-- Рекламный Баннер №6 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b6a.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3>
                     Декоративные<br />крепежные элементы
                   </h3>
                </div>
                <a href="/dekorativnie_krepezhnie_elementi_sd/" class="link">перейти</a>
              </div>
            </div>            
          </li>
      <!-- Рекламный Баннер №7 -->
          <li>
            <div class="slide" style="background: url(<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner/b7w.jpg);">
              <div class="inner">
                <div class="textHeader">
                   <h3g>
                     <br />Удобное<br />хранение
                   </h3g>
                </div>
                <a href="/reguliruemye_sistemy/" class="link">перейти</a>
              </div>
            </div>            
          </li>
        </ul>
      </div>
      <div class="navControl jcarousel-pagination">
      </div>
    </div>
  </div>        

  <div class="right">
    <div class="slider rightSlider">
      <div class="container jcarousel">
        <ul>
          
          
          
          <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker-new">НОВИНКА</div>
                <div class="textHeader">
                  <img alt="Крепеж для вагонки" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/1.jpg">
                  <h3>Крепеж для вагонки</h3>
                </div>
                <a href="/catalog/krepezh_dlya_vagonki/" class="link">перейти</a>
              </div>
            </div>
          </li>

          <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 16 руб./уп.</div>
                <div class="textHeader">
                  <img alt="Крепеж для вагонки" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/2.jpg">
                  <h3>Кабельные стяжки эконом</h3>
                </div>
                <a href="/kabel_nye_styazhki_ekonom/" class="link">перейти</a>
              </div>
            </div>
          </li>
          
          <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 50 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Крепеж для вагонки" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/3.jpg">
                  <h3><br>Термоусаживаемые трубки RCK токостенные, стандартные с клеем</h3>
                </div>
                <a href="/termousazhivaemye_izdeliya_radpol/" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №4 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 39 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Перчатки полиэстер" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p4.jpg">
                  <h3>Перчатки полиэстер</h3>
                </div>
                <a href="/perchatki/perchatki_poliester_rees.html" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №5 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 6,88 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Скобяные изделия" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p5.jpg">
                  <h3>Скобяные изделия</h3>
                </div>
                <a href="/skobyanye_izdeliya/" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №6 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 42,43 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Диски абразивные" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p6.jpg">
                  <h3>Диски абразивные</h3>
                </div>
                <a href="/diski_abrazivnye/" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №7 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 11,3 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Хомуты" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p7.jpg">
                  <h3>Хомуты</h3>
                </div>
                <a href="/inzhenernie_sistemi/homut_stalnoj_s_rezinovim_uplotnitelem_santehnicheskij.html" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №8 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 4,21 руб./м.</div>
                <div class="textHeader">
                  <img alt="Веревка крученная джутовая на ролике" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p8.jpg">
                  <h3>Веревка крученная джутовая</h3>
                </div>
                <a href="/catalog/verevka_kruchennaya_dzhutovaya_na_rolike/" class="link">перейти</a>
              </div>
            </div>
          </li>
          <!-- Правый Баннер №9 -->
           <li>
            <div class="slide">
			  <div class="inner">
                <div class="price-stiker">от 442,67 руб./шт.</div>
                <div class="textHeader">
                  <img alt="Полки ламинированные со скрытым креплением" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>banner_right/p91.jpg">
                  <h3>Полки со скрытым креплением</h3>
                </div>
                <a href="/catalog/polka_so_skrytym_krepleniem/" class="link">перейти</a>
              </div>
            </div>
          </li>
          
        </ul>
      </div>
      <div class="navControl jcarousel-pagination">
      </div>
    </div>
  </div>

</div>

<div class="mainCats">
  <div class="mainCatsCategories">
    <div class="controls">
      <a href="#" class="prev">&nbsp;</a>
      <a href="#" class="next">&nbsp;</a>
    </div>
   
    <div class="container jcarousel catSlider">
      <ul class="catList" id="mainCatCarouselHeader">
        <?php if(count($this->vars['feeds'])) : 
							   		 $this->vars['foreach']['feeds']['count'] = count($this->vars['feeds']);
							   		 $this->vars['foreach']['last']['count'] = count($this->vars['feeds']);
							   		 foreach($this->vars['feeds'] as $this->vars['foreach']['feeds']['key'] => $this->vars['item']):
							            $this->vars['foreach']['key'] = $this->vars['foreach']['feeds']['key']; ?>
        	<li><a href="javascript:void(0)" class="<?php if(isset($this->vars['item']['icon'])) echo $this->vars['item']['icon']; ?>" item-id="<?php if(isset($this->vars['item']['id'])) echo $this->vars['item']['id']; ?>"><?php if(isset($this->vars['item']['name'])) echo $this->vars['item']['name']; ?></a></li>
        <?php endforeach; ?><?php endif; ?>
      </ul>
    </div>
  </div>        
  <div class="mainCatsGoods">
    <div id="feddsAllProducts" style="display:none">
      <?php if(count($this->vars['feeds'])) : 
							   		 $this->vars['foreach']['feeds']['count'] = count($this->vars['feeds']);
							   		 $this->vars['foreach']['last']['count'] = count($this->vars['feeds']);
							   		 foreach($this->vars['feeds'] as $this->vars['foreach']['feeds']['key'] => $this->vars['feedItem']):
							            $this->vars['foreach']['key'] = $this->vars['foreach']['feeds']['key']; ?>
      <?php $this->vars['feedId'] = $this->vars['feedItem']['id']; ?>
      <ul class="goodsList" item-id="<?php if(isset($this->vars['feedId'])) echo $this->vars['feedId']; ?>">
      	<?php if(count($this->vars['feedsProduct'][$this->vars['feedId']])) : 
							   		 $this->vars['foreach']['feedsProduct.$feedId']['count'] = count($this->vars['feedsProduct'][$this->vars['feedId']]);
							   		 $this->vars['foreach']['last']['count'] = count($this->vars['feedsProduct'][$this->vars['feedId']]);
							   		 foreach($this->vars['feedsProduct'][$this->vars['feedId']] as $this->vars['foreach']['feedsProduct_$feedId']['key'] => $this->vars['item']):
							            $this->vars['foreach']['key'] = $this->vars['foreach']['feedsProduct_$feedId']['key']; ?>
          <li>
            <a href="<?php if(isset($this->vars['item']['url'])) echo $this->vars['item']['url']; ?>">
              <div class="itemimage"><img alt="" src="<?php if(isset($this->vars['item']['img'])) echo $this->vars['item']['img']; ?>" /></div>
              <span class="title"><?php if(isset($this->vars['item']['title'])) echo $this->vars['item']['title']; ?></span>
              <span class="price">
                <?php if (isset($this->vars['item']['mod']) && $this->vars['item']['mod']  ): ?>
                	<?php if(isset($this->vars['item']['mod']['price'])) echo $this->vars['item']['mod']['price']; ?><i>/ за <?php if(isset($this->vars['item']['mod']['pack_size'])) echo $this->vars['item']['mod']['pack_size']; ?> <?php if(isset($this->vars['item']['mod']['pack_unit_name'])) echo $this->vars['item']['mod']['pack_unit_name']; ?></i>
                <?php else: ?>
                	<?php if(isset($this->vars['item']['price'])) echo $this->vars['item']['price']; ?><i>/ за <?php if(isset($this->vars['item']['pack_size'])) echo $this->vars['item']['pack_size']; ?> <?php if(isset($this->vars['item']['pack_unit_name'])) echo $this->vars['item']['pack_unit_name']; ?></i>
                <?php endif; ?>
              </span>
            </a>
          </li>    
        <?php endforeach; ?><?php endif; ?>
      </ul>
      <?php endforeach; ?><?php endif; ?>
    </div>
    <div class="controls">
      <a href="#" class="prev">&nbsp;</a>
      <a href="#" class="next">&nbsp;</a>
    </div>
    <div class="container jcarousel itemsSlider" id="mainCatCarousel"></div>
  </div>
</div>


<div class="mainManufacturers contentContainer">
  <?php if($core->lib->widget("Vendors")): ?>
<?php $core->widgets->Vendors()->setting("limit", "5"); ?>
<?php $core->widgets->Vendors()->setting("random", "1"); ?>

<?php $core->widgets->Vendors()->appendSettings(); $core->widgets->Vendors()->main(); endif; ?>
  
  <?php if (isset($this->vars['VendorsOut']) && $this->vars['VendorsOut']  ): ?>
  <!--
  <p>
	Компания «Русконект» является одним из ведущих игроков на рынке оптовых поставок высококачественного 
	<b>крепежа</b> и сопутствующих товаров от ведущих отечественных и зарубежных производителей. Всегда в наличии – <b>нержавеющий крепеж оптом</b> в широчайшем ассортименте и по самым выгодным ценам.
</p>
<p>
	 Мы давно работаем на рынке оптовых поставок 
	<b>крепежных</b> изделий, обеспечивая своим заказчикам и постоянным партнерам бесперебойные поставки всех видов <b>крепежа</b> от гвоздей до такелажных цепей и прочих массивных грузовых и <b>строительных креплений</b>. Нашими клиентами являются предприятия всех форм собственности и различных размеров, которые осуществляют свою деятельность в области промышленного производства, строительства, отделки и ремонта, изготовления мебели, эксплуатации коммуникационных и коммунальных линий, розничной торговли строительными материалами и мн. др.
</p>
-->
  <h2>Производители и бренды</h2>
  
  <ul class="manList">     
    <?php if(count($this->vars['VendorsOut'])) : 
							   		 $this->vars['foreach']['VendorsOut']['count'] = count($this->vars['VendorsOut']);
							   		 $this->vars['foreach']['last']['count'] = count($this->vars['VendorsOut']);
							   		 foreach($this->vars['VendorsOut'] as $this->vars['foreach']['VendorsOut']['key'] => $this->vars['item']):
							            $this->vars['foreach']['key'] = $this->vars['foreach']['VendorsOut']['key']; ?>
    <li>
      <a href="/ru/shop/vendor/id/<?php if(isset($this->vars['item']['id'])) echo $this->vars['item']['id']; ?>/">
        <div class="manImage">
          <?php if (isset($this->vars['item']['text_image2']) && $this->vars['item']['text_image2']  ): ?><img alt="" src="<?php if(isset($this->vars['item']['text_image2'])) echo $this->vars['item']['text_image2']; ?>" /><?php endif; ?>
          <span class="caption"><?php if(isset($this->vars['item']['sub_description'])) echo $this->vars['item']['sub_description']; ?>	</span>
        </div>
        <div class="manLogo">
          <?php if (isset($this->vars['item']['image_original']) && $this->vars['item']['image_original']  ): ?><img alt="" src="<?php if(isset($this->vars['item']['image_original'])) echo $this->vars['item']['image_original']; ?>" /><?php endif; ?>
        </div>
      </a>
    </li>            
    <?php endforeach; ?><?php endif; ?>
  </ul>
  <?php endif; ?>
</div>

<div class="catalogIndex">
  <h2>Продукция</h2>
  <div class="preview">

  	<?php if($core->lib->widget("ProductGroups")): ?>
<?php $core->widgets->ProductGroups()->setting("parent_id", "31"); ?>

<?php $core->widgets->ProductGroups()->appendSettings(); $core->widgets->ProductGroups()->main(); endif; ?>

    <ul class="visible">
      <?php if(count($this->vars['ProductGroupsOut'])) : 
							   		 $this->vars['foreach']['ProductGroupsOut']['count'] = count($this->vars['ProductGroupsOut']);
							   		 $this->vars['foreach']['last']['count'] = count($this->vars['ProductGroupsOut']);
							   		 foreach($this->vars['ProductGroupsOut'] as $this->vars['foreach']['ProductGroupsOut']['key'] => $this->vars['item']):
							            $this->vars['foreach']['key'] = $this->vars['foreach']['ProductGroupsOut']['key']; ?>
      <li><a href="<?php if(isset($this->vars['item']['url'])) echo $this->vars['item']['url']; ?>" data-category="<?php if(isset($this->vars['item']['id'])) echo $this->vars['item']['id']; ?>" title="<?php if(isset($this->vars['item']['name'])) echo $this->vars['item']['name']; ?>"><?php if(isset($this->vars['item']['name'])) echo $this->vars['item']['name']; ?></a></li>
      <?php endforeach; ?><?php endif; ?>
    </ul>

  </div>
</div>


<div class="mainManufacturers contentContainer" style="display:none">
  <!--
  <p>
	 В нашем лице вы сможете найти исключительно надежного поставщика, который в состоянии закрыть любые потребности организаций на 
	<b>крепежные изделия в Москве</b> вне зависимости от эксклюзивности этих потребностей и необходимых объемов поставок. Постоянно в наличии – тысячи товарных позиций, причем ассортиментный перечень увеличивается буквально изо дня в день, а складские запасы растут.
</p>
<p>
	<h3>Преимущества поставок строительного крепежа от компании «Русконект»</h3>
<p>
	 Говоря о преимуществах нашей компании, мы сознательно не будем прибегать к громогласным и очень красивым по форме, но пустым по содержанию рекламным слоганам и «кричалкам». Компании, не первый год сотрудничающие с нами и регулярно покупающие
	<b> нержавеющий</b> <b>строительный крепеж оптом</b>, прекрасно знают о том, что нам не свойственно выпячивать себя и тем более пускать пыль в глаза. Поэтому мы ограничимся лишь беспристрастными достоверными фактами, которые помогут вам убедиться в том, что мы предлагаем действительно качественный <b>высокопрочный крепеж</b> и оказываем услуги самого высокого уровня:
</p>
<p>
	 · Мы работаем на рынке обеспечения поставок 
	<b>крепежа оптом в Москве</b> и Санкт-Петербурге уже много лет. Все эти годы мы напряженно трудились и активно развивались, налаживая новые прямые поставки, увеличивая ассортимент и складские запасы, повышая качество услуг и завоевывая все большую долю рынка, а также признание со стороны заказчиков и безупречную деловую репутацию. Мы по праву гордимся тем, что многие крупные компании уже не один год доверяют обеспечение их потребностей в <b>высокопрочном крепеже</b> компании «Русконект», выбирая нас генеральными поставщиками и постоянными партнерами.
</p>
<p>
	 · Мы поставляем практически любой 
	<b>крепеж</b>, востребованный на отечественном рынке. <b>Крепеж мелкий</b>, <b>строительный крепеж</b>, <b>грузовой крепеж</b>, приспособления для выполнения такелажных работ, петли, изделия для выполнения электромонтажных работ. Это лишь малая толика нашего <b>крепежного</b> ассортимента.
</p>
<p>
	 · Прямые поставки 
	<b>высокопрочного крепежа</b> от производителей и огромные товарные обороты позволяют нам формировать самую привлекательную стоимость предлагаемой продукции и предоставлять наиболее активным покупателям дополнительные скидки и особые условия обслуживания (индивидуальный менеджер, эксклюзивные предложения по оплате и отгрузке товара, товарная поддержка и т.д.);
</p>
<p>
	 · Помимо действительно огромного прайса на 
	<b>нержавеющий крепеж оптом</b>, мы предлагаем не менее внушительный список сопутствующих товаров. Это ящики для инструментов, шнуры, шпагаты и веревки, мебельные амортизаторы, стеллажи и прочие элементы для организации экспозиции;
</p>
<p>
	 · Также стоит отметить, что мы продаем 
	<b>крепежные изделия</b> не только крупным, но и мелким оптом. Следовательно, нашими постоянными и безмерно уважаемыми клиентами могут быть и молодые компании, и организации, бизнес которых не требует очень больших поставок
</p>
<p>
	 · Весь строительный 
	<b>высокопрочный крепёж</b> <b>оптом</b>, предлагаемый компанией «Русконект» имеет высочайшее качество, что подтверждено всей необходимой документацией.
</p>
<p>
	 Разумеется, это далеко не полный перечень аргументов в пользу того, чтобы покупать 
	<b>строительный крепеж оптом</b> в нашей организации. Но мы думаем, что и этих пунктов будет вполне достаточно, чтобы понять: мы – надежный поставщик, проверенный временем и имеющий действительно безупречную репутацию как среди покупателей, так и в профессиональной бизнес-среде.
</p>

  <br>
	<h2>Разнообразие применения высокопрочного крепежа от компании «Русконект»</h2>

<p>
	 Как уже говорилось, в ассортименте нашего предприятия можно найти самые различные 
	<b>крепежные изделия</b> и сопутствующие товары. Наши <b>крепежи</b> применяются, прежде всего, на разных этапах строительства, ремонта и отделки. Но совсем не ограничиваются только этим – товарный перечень «Русконект» значительно шире, чем только <b>строительный крепеж</b>. Остановимся на этом немного подробнее.
</p>
<p>
	<b>Грузовой крепеж</b> (грузоподъемные цепи, вантовые крепления, скобы, звенья, карабины, крюки и много другое) позволяют выполнять самые различные, в том числе и очень сложные погрузочно-разгрузочные и такелажные работы. А качество нашего <b>надежного крепежа</b> позволяет быть уверенным в надежности всей такелажной системы и безопасности при проведении данного типа работ.
</p>
<p>
	<b>Мелкий крепеж</b> имеет самое богатое ассортиментное разнообразие и применяется при выполнении огромного количества работ – как сугубо профессиональных, так и бытовых. Поэтому именно такие <b>крепежи</b> особенно активно покупаются не только строительными организациями, но предприятиями торговли, предлагающими крепежные изделия конечным пользователям и небольшим подрядным организациям и бригадам.
</p>
<p>
	 Скобяные изделия, представленные в нашем каталоге – это также 
	<b>высокопрочный крепёж</b>, представляющий собой все виды петель, задвижек, щеколды и ручек. Отличное качество, бесшумность, длительность эксплуатации – все это обеспечивают <b>крепежи</b> от предприятия «Русконект»! <b>Весь крепеж</b> безупречно надежен и долговечен – это подтверждено годами его продажи и использования на самых различных объектах, в том числе и в высоконагруженных конструкциях. Наши <b>крепежи</b> справляются с любыми задачами исключительно на «отлично»!
</p>
<p>
	 Постройки, сооружения и конструкции, в которых используется 
	<b>строительные крепления</b> «Русконект» производства ведущих компаний отрасли, отлично служат годами и десятилетиями, обеспечивая герметичность соединения, надежность и устойчивость конструкции. Покупайте <b>строительный крепеж оптом</b> у нас – и качество вашего строительства будет по-настоящему безупречным!
</p>
<p>
	<b>Где купить строительные крепления и нержавеющий крепеж оптом в Москве?</b>
</p>
<p>
	 Компаний, которые предлагают 
	<b>нержавеющий крепеж в Москве оптом</b>, существует множество. Но лишь немногие из них могут обеспечивать поставки любых объемов в кратчайшие сроки, иметь тысячи и тысячи товарных позиция в наличии и предоставлять самые выгодные условия сотрудничества. И «Русконект» - как раз одна из таких компаний.
</p>
<p>
	 Мы никогда не ставим во главу угла получение сиюминутной выгоды. Наша стратегическая задача – налаживание тесных партнерских отношений с потребителями 
	<b>строительных креплений</b> и любых других <b>крепежей</b> и долгосрочное сотрудничество на долгосрочной основе.
</p>
<p>
	 Поэтому, если вам необходим качественный и недорогой 
	<b>крепёж оптом</b> и надежный поставщик, всегда и в полном объеме выполняющий свои обязательства, то мы будем рады сотрудничеству с вами, предлагая самые лучшие условия для поставок с<b>троительного крепления</b> и прочих изделий!
</p>
<p>
	 По всем вопросам, касающимся поставок 
	<b>крепежей оптом</b> и мелким оптом, обязательно звоните нам! Компетентные и всегда исключительно доброжелательные сотрудники нашего офиса с радостью ответят на все ваши вопросы, предоставят любую дополнительную информацию про <b>крепеж потом</b> и расскажут еще больше о преимущества сотрудничества именно с нашей организацией. Мы уверены, что наше знакомство обязательно перерастет в постоянное сотрудничество и взаимовыгодное партнерство.
</p>
<p>
	 Будем рады видеть вашу компанию в числе наших заказчиков. Качественные 
	<b>крепежные изделия</b> оптом – только в компании «Русконект»! Мы – за <b>высококачественный крепеж</b>!
</p>-->
</div>