<? $this->md5_compil='7a0fbb804c49842313e8e56e33a958ae'; ?>

<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.templates.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/md5crypt.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/hotkey/jquery.hotkey.js" type="text/javascript"></script>
<script  src="/plugins/codemirror/lib/codemirror-compressed.js?v2" type="text/javascript"></script>
<link  href="/plugins/codemirror/lib/codemirror.css?v2" rel="stylesheet">


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Шаблоны <small>Редактор шаблонов сайта</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>

