<? $this->md5_compil='57a8b576a18d0f066487716563f2d874'; ?>
<div class="control-group">
  <label class="control-label">ID Группы Вконтакте</label>
  <div class="controls">
    <input type="text"  module-id="<?php if(isset($this->vars['moduleId'])) echo $this->vars['moduleId']; ?>" name="social_vk_group" value="<?php if(isset($this->vars['moduleInfo']['social_vk_group'])) echo $this->vars['moduleInfo']['social_vk_group']; ?>">
  </div>
</div>