<? $this->md5_compil='b0c6b095574bf9315c6b9d831ca610cd'; ?>
<script type="text/javascript" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.min.js"></script>
<script type="text/javascript" src="/plugins/ckeditor/ckeditor.js"></script>
<script type="text/javascript" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/nestable/jquery.nestable.js"></script>
<script type="text/javascript" src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.site_control.js"></script>
<link rel="stylesheet" type="text/css" href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/nestable/jquery.nestable.css" /> 
<link rel="stylesheet" type="text/css" href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/jquery-tags-input/jquery.tagsinput.css" />  
<?php if(isset($this->vars['controller_content'])) echo $this->vars['controller_content']; ?>
