<? $this->md5_compil='5920f254235aaa77e92da8b369aa3a90'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.core-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.excheck-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/js/jquery.ztree.exedit-3.5.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>routes/theme.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/bootstrap-wizard/jquery.bootstrap.wizard.min.js" type="text/javascript"></script>
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>/css/ncity_admin.css" rel="stylesheet">
<link  href="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>assets/ztree/css/zTreeStyle.css" rel="stylesheet">


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Управление внешним видом магазина</h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>
<div class="row-fluid">
  <a href="#/" class="icon-btn span2">
    <i class="icon-picture"></i>
    <div>Темы оформления</div>
  </a>
  <a href="/ru/templates/" class="icon-btn span2">
    <i class="icon-qrcode"></i>
    <div>HTML редактор</div>
  </a>
  <!--
  <a href="/ru/templates/#/css/" class="icon-btn span2">
    <i class="icon-tasks"></i>
    <div>CSS редактор</div>
  </a>
  
  <a href="#" class="icon-btn span2">
    <i class="icon-folder-close"></i>
    <div>Файлы</div>
  </a>-->
</div>


