<? $this->md5_compil='a814aaf76fe1081e7c4e35ab365651e9'; ?>

<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.users.js" type="text/javascript"></script>


<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Пользователи <small>Пользователи кабинета, менеджеры</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>

