<? $this->md5_compil='f3027e5e94058190134ff40b7bb0c527'; ?>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/director.js" type="text/javascript"></script>
<script src="<?php if(isset($this->vars['static'])) echo $this->vars['static']; ?>modules/admin.notice.js" type="text/javascript"></script>
<script src="/plugins/ckeditor/ckeditor.js" type="text/javascript"></script>



<div class="row-fluid">
   <div class="span12">
     <h3 class="page-title">Нотификации <small>уведомления на события в системе</small></h3>
     <ul class="breadcrumb" id="crumbs"></ul>
   </div>
</div>

